[package]
name = "llama-cpp-sys-2"
description = "Low Level Bindings to llama.cpp"
version = "0.1.69"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/utilityai/llama-cpp-rs"
links = "llama"

include = [
    "build.rs",
    "/src",
    "/llama.cpp/ggml/src/ggml.c",
    "/llama.cpp/ggml/include/ggml.h",
    "/llama.cpp/ggml/src/ggml-alloc.c",
    "/llama.cpp/ggml/include/ggml-alloc.h",
    "/llama.cpp/ggml/src/ggml-backend.c",
    "/llama.cpp/ggml/include/ggml-backend.h",
    "/llama.cpp/ggml/src/ggml-backend-impl.h",
    "/llama.cpp/ggml/src/ggml-cuda.cu",
    "/llama.cpp/ggml/include/ggml-cuda.h",
    "/llama.cpp/ggml/src/ggml-impl.h",
    "/llama.cpp/ggml/src/ggml-metal.m",
    "/llama.cpp/ggml/src/ggml-metal.metal",
    "/llama.cpp/ggml/include/ggml-metal.h",
    "/llama.cpp/ggml/src/ggml-mpi.c",
    "/llama.cpp/ggml/src/ggml-mpi.h",
    "/llama.cpp/ggml/src/ggml-opencl.cpp",
    "/llama.cpp/ggml/src/ggml-opencl.h",
    "/llama.cpp/ggml/src/ggml-quants.c",
    "/llama.cpp/ggml/src/ggml-quants.h",
    "/llama.cpp/src/llama.cpp",
    "/llama.cpp/src/llama-impl.h",
    "/llama.cpp/src/llama-vocab.h",
    "/llama.cpp/src/llama-vocab.cpp",
    "/llama.cpp/src/llama-grammar.h",
    "/llama.cpp/src/llama-grammar.cpp",
    "/llama.cpp/src/llama-sampling.h",
    "/llama.cpp/src/llama-sampling.cpp",
    "/llama.cpp/include/llama.h",
    "/llama.cpp/src/unicode.h",
    "/llama.cpp/src/unicode.cpp",
    "/llama.cpp/src/unicode-data.h",
    "/llama.cpp/src/unicode-data.h",
    "/llama.cpp/src/unicode-data.cpp",
    "/llama.cpp/ggml/src/ggml-common.h",
    "/llama.cpp/ggml/src/ggml-cuda",
    "/llama.cpp/ggml/sgemm.h",
    "/llama.cpp/ggml/src/ggml-cuda/*",
    "/llama.cpp/ggml/src/ggml-cuda/template_instances/*",
    "/llama.cpp/ggml/src/ggml-aarch64.h",
    "/llama.cpp/ggml/src/ggml-aarch64.c",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = { workspace = true }
cc = { workspace = true, features = ["parallel"] }
once_cell = "1.19.0"

[features]
cuda = []
metal = []
dynamic_link = []
vulkan = []
native = []
blas = []
hipblas = []
clblast = []
compat = []
cuda_dmmv = []
cuda_mmq = []
openblas = []
blis = []